name: CI

on:
  push: [ main ]
 pull_request:
  branches: [ main ]
  
 workflow_dispatch:
 
jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout
      
      - name: run a one-line script
        run: echo hello. world!
        
     - name: run a multi-line script
       run:
       echo Add other actions to build,
       echo test, and deploy your project.
